branch-defaults:
  main:
    environment: erp-backend-prod
    group_suffix: null
global:
  application_name: erp-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
